spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/modeldb}
    username: ${SPRING_DATASOURCE_USERNAME:model_user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
